services:
  # SERVICES
  # fusionauth:
  #   image: fusionauth/fusionauth-app:latest
  #   container_name: fusionauth
  #   environment:
  #     DATABASE_URL: jdbc:postgresql://${FUSIONAUTH_DB_HOSTNAME}:${FUSIONAUTH_DB_PORT}/fusionauth
  #     DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
  #     DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
  #     DATABASE_USERNAME: ${FUSIONAUTH_DB_USER}
  #     DATABASE_PASSWORD: ${FUSIONAUTH_DB_PASS}
  #     restart: unless-stopped
  #   volumes:
  #     - fa_config:/usr/local/fusionauth/config
  #   ports:
  #     - target: 9011
  #       published: ${FUSIONAUTH_PORT}
  broker:
    container_name: broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - target: 9001
        published: ${BROKER_PORT}

  # # BACKEND
  # backend:
  #   container_name: backend
  #   build: 
  #     context: ./backend
  #   environment:
  #     BACKEND_URL: ${BACKEND_URL}
  #     BIGBASE_URL: ${BIGBASE_URL}
  #     FUSIONAUTH_URL: ${FUSIONAUTH_URL}
  #     WINDS_DB_HOSTNAME: ${WINDS_DB_HOSTNAME}
  #     WINDS_DB_PORT: ${WINDS_DB_PORT}
  #     CLIENT_ID: ${CLIENT_ID}
  #     CLIENT_SECRET: ${CLIENT_SECRET}
  #     APPLICATION_ID: ${APPLICATION_ID}
  #     API_KEY: ${API_KEY}
  #   ports:
  #     - target: 8000
  #       published: ${BACKEND_PORT}

  # # FRONTENDS
  # bigbase:
  #   container_name: bigbase
  #   build: 
  #     context: ./bigbase
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - target: 80
  #       published: ${BIGBASE_PORT}
  # bigtop:
  #   container_name: bigtop
  #   build: 
  #     context: ./bigtop
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - target: 80
  #       published: ${BIGTOP_PORT}

# volumes:
#   fa_config: