#!/usr/bin/python

import os, sys
try:
    file = sys.argv[1]
except:
    file = "docker-compose.yml"
os.system(f"sudo docker-compose -f {file} down")
os.system(f"sudo docker-compose -f {file} build")
os.system(f"sudo docker-compose -f {file} up")
