services:
  backend:
    container_name: backend
    build: "./backend"
    networks:
      - backend
      - ext
    ports:
      - 8000:8000

  bigbase:
    container_name: bigbase
    build: 
      context: ./bigbase
      dockerfile: Dockerfile
    ports:
      - 8001:80
    
  bigtop:
    container_name: bigtop
    build: 
      context: ./bigtop
      dockerfile: Dockerfile
    ports:
      - 8002:80

