services:
  winds_database:
    container_name: winds_database
    image: postgres
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: winds
    restart: on-failure
    ports:
      - target: 5432
        published: ${WINDS_DB_PORT}
    volumes:
      - ./postgres/winds:/docker-entrypoint-initdb.d
      - winds_data/:/var/lib/postgresql/data

  fusionauth_database:
    container_name: fusionauth_database
    image: postgres
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fusionauth
    ports:
      - target: 5432
        # published: ${FUSIONAUTH_DB_PORT}
    restart: on-failure
    volumes:
      - fa_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on: 
      - fusionauth_database
    container_name: fusionauth
    environment:
      DATABASE_URL: jdbc:postgresql://${FUSIONAUTH_DB_URL}:${FUSIONAUTH_DB_PORT}/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DB_USER}
      DATABASE_PASSWORD: ${FUSIONAUTH_DB_PASS}
      restart: unless-stopped
    volumes:
      - fa_config:/usr/local/fusionauth/config
    ports:
      - target: 9011
        published: ${FUSIONAUTH_PORT}

  broker:
    container_name: broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - target: 9001
        published: ${BROKER_PORT}

volumes:
  fa_config:
  fa_data:
  winds_data: