FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN ["apt", "update", "-y"]
RUN ["apt", "install", "python3.9", "python3-pip", "memcached", "-y"]
RUN ["service", "memcached", "start"]
COPY . /app
WORKDIR /app
RUN ["pip", "install", "-r", "requirements.txt"]
CMD ["hypercorn", "app:app", "--bind", "backend"]